import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AKARSH JAIN PORTFOLIO",
  description: "Generated by Akarsh Jain",
};

import MouseTrail from "@/components/mousetrail";
import SpeakerButton from "@/components/speakerbutton";
import Chatbot from "@/components/chatbot";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050505] text-white`}
      >
        {/* Global ambient glowing background filter */}
        <div 
          className="fixed inset-0 z-[-1] pointer-events-none overflow-hidden bg-cover bg-center"
          style={{ backgroundImage: "url('/space-bg.png')" }}
        >
          <div className="absolute inset-0 bg-black/40" />
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-600/20 rounded-full blur-[150px]" />
          <div className="absolute bottom-1/4 right-1/4 w-[30rem] h-[30rem] bg-purple-600/15 rounded-full blur-[150px]" />
        </div>
        
        <MouseTrail />
        <div className="relative z-0">
          {children}
        </div>
        
        <SpeakerButton />
        <Chatbot />
      </body>
    </html>
  );
}
